version: '3.8'

services:
  stockmanager:
    image: ${REGISTRY_URL}/${IMAGE_NAME}:${TAG}
    env_file: .env
    ports:
      - "${HOST_PORT:-8005}:${CONTAINER_PORT:-8005}"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=stockmanager.settings.production
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOST=${ALLOWED_HOST}
    command: >
      sh -c "/app/venv/bin/gunicorn stockmanager.wsgi:application \
      --bind 0.0.0.0:$CONTAINER_PORT \
      --workers ${WORKERS:-2} \
      --timeout ${TIMEOUT:-60} \
      --log-level ${LOG_LEVEL:-info} \
      --access-logfile /app/logs/gunicorn_access.log \
      --error-logfile /app/logs/gunicorn_error.log"
    restart: unless-stopped
    
  # Service pour les tests (optionnel)
  stockmanager-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=stockmanager.settings.development
    command: >
      bash -c "source /app/venv/bin/activate && \
               python manage.py test"
    profiles: ["test"]
