# Generated by Django 5.2.4 on 2025-07-08 16:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="Опис")),
                (
                    "cout_achat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Собівартість",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Ціна продажу",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Дата зміни"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="Mouvement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[("entree", "Надходження"), ("sortie", "Вихід")],
                        max_length=10,
                        verbose_name="Тип операції",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="Кількість")),
                (
                    "date_mouvement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операції"
                    ),
                ),
                ("commentaire", models.TextField(blank=True, verbose_name="Коментар")),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.produit",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рух товару",
                "verbose_name_plural": "Рухи товарів",
                "ordering": ["-date_mouvement"],
            },
        ),
    ]
