# Generated by Django 5.2.4 on 2025-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="seuil_alerte",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Мінімальна кількість для попередження",
                verbose_name="Поріг попередження",
            ),
        ),
    ]
