# Generated by Django 5.2.4 on 2025-07-08 16:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_produit_seuil_alerte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="prix_vente",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Базова ціна продажу",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Ціна продажу (базова)",
            ),
        ),
        migrations.CreateModel(
            name="PrixVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Ціна продажу",
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True,
                        help_text="Клієнт або контекст для цієї ціни",
                        max_length=200,
                        verbose_name="Клієнт",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Чи активна ця ціна для використання",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Причина зміни ціни або деталі переговорів",
                        verbose_name="Коментар",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prix_vente_historique",
                        to="inventory.produit",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ціна продажу",
                "verbose_name_plural": "Ціни продажу",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="mouvement",
            name="prix_vente_utilise",
            field=models.ForeignKey(
                blank=True,
                help_text="Ціна продажу використана для цієї операції (тільки для виходів)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.prixvente",
                verbose_name="Ціна продажу використана",
            ),
        ),
    ]
