# Generated by Django 5.2.4 on 2025-07-10 14:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_produit_prix_vente_prixvente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Зображення товару",
                null=True,
                upload_to="produits/",
                verbose_name="Фото товару",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="cout_achat",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Базова собівартість товару",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Собівартість (базова)",
            ),
        ),
        migrations.CreateModel(
            name="CoutAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cout",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Собівартість",
                    ),
                ),
                (
                    "fournisseur",
                    models.CharField(
                        blank=True,
                        help_text="Постачальник або контекст для цієї вартості",
                        max_length=200,
                        verbose_name="Постачальник",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Чи активна ця вартість для використання",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Причина зміни вартості або деталі закупівлі",
                        verbose_name="Коментар",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cout_achat_historique",
                        to="inventory.produit",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Собівартість",
                "verbose_name_plural": "Собівартості",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="mouvement",
            name="cout_achat_utilise",
            field=models.ForeignKey(
                blank=True,
                help_text="Собівартість використана для цієї операції (тільки для надходжень)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.coutachat",
                verbose_name="Собівартість використана",
            ),
        ),
    ]
